import { Figtree } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import { SupabaseProvider } from "@/providers/Supabase-Provider";
const font = Figtree({ subsets: ["latin"] });

export const metadata = {
  title: "Spotify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <SupabaseProvider>
          <SideBar>{children}</SideBar>
        </SupabaseProvider>
      </body>
    </html>
  );
}
